name: Vault
on:
  - workflow_dispatch
jobs:
  env:
    name: Get .env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
        
      # Use GitHub secrets to store Vault token
      - name: Populate .env
        run: npx dotenv-vault pull -m ${{ secrets.DOTENV_ME }} -y
      
      # .env file is now available in the workspace
      - name: Show all files
        run: ls -la
        
      # and visible for the app
      - name: Run app
        run: npm run start
